# Definición de la API y versión utilizada
apiVersion: apps/v1

# Especifica que este archivo describe un objeto de tipo Deployment
kind: Deployment

# Metadatos asociados al Deployment
metadata:
  # Nombre del Deployment
  name: msvc-cursos

# Especificaciones del Deployment
spec:
  # Número de réplicas (instancias) del pod que se desea ejecutar
  replicas: 3

  # Selector para identificar los pods gestionados por este Deployment
  selector:
    matchLabels:
      # Etiqueta utilizada para identificar los pods de este Deployment
      app: msvc-cursos

  # Plantilla para la configuración de los pods
  template:
    metadata:
      # Etiquetas aplicadas a los pods
      labels:
        app: msvc-cursos

    # Especificaciones de los contenedores dentro del pod
    spec:
      containers:
        - name: cursos # Nombre del contenedor
          image: chanochoca/cursos:latest # Imagen de Docker utilizada para el contenedor

          # Puertos expuestos por el contenedor
          ports:
            - containerPort: 8002 # Puerto en el que la aplicación escucha

          # Variables de entorno para la configuración del contenedor
          env:
            - name: PORT
              value: "8002" # Puerto en el que la aplicación escucha (como variable de entorno)
            - name: DB_HOST
              value: "postgres16:5432" # Dirección y puerto del servidor de base de datos PostgreSQL
            - name: DB_DATABASE
              value: msvc-cursos # Nombre de la base de datos a utilizar
            - name: DB_USERNAME
              value: postgres # Nombre de usuario para acceder a la base de datos
            - name: DB_PASSWORD
              value: postgres # Contraseña para el usuario de la base de datos
            - name: USUARIOS_URL
              value: "msvc-usuarios:8001" # URL del servicio de usuarios
